- name: provision docker containers
  hosts: localhost
  tasks:
    - name: Start Ubuntu contianers
      docker_container:
         image: ubuntuansible2
         name: "ubunt{{item}}"
         state: present
         ports:
            - "210{{item}}:22"
            - "810{{item}}:80"
      with_sequence: start=1 end=2


    - name: Start centos contianers
      docker_container:
         image: ansible-centos2
         name: "cento{{item}}"
         state: present
         ports:
            - "230{{item}}:22"
            - "830{{item}}:80"
      with_sequence: start=1 end=2

