- name: provision docker containers
  hosts: localhost
  tasks:
    - name: Start Ubuntu contianers
      docker_container:
         image: ubuntuansible
         state: present
         ports:
            - "210{{iten}}:22"
            - "810{{item}}:80"
      with_sequences: start=1 end=2


    - name: Start centos contianers
      docker_container:
         image: ansible-centos
         state: present
         ports:
            - "230{{iten}}:22"
            - "830{{item}}:80"
      with_sequences: start=1 end=2

